name: build-scan-and-comment
on: [pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short SHA
        run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.GHA_SHA }}

      - uses: lacework/lw-scanner-action@v1.4.0
        name: Scan container image for vulnerabitilies using Lacework
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ env.GHA_SHA }}
          SAVE_RESULTS_IN_LACEWORK: true
          RESULTS_IN_GITHUB_SUMMARY: true

      - name: Change formatting for PR
        run: |
            echo "# Lacework Inline Scanner Result" > pr-results.md
            echo "## Container: \`$REGISTRY/$IMAGE_NAME:$GHA_SHA\`" >> pr-results.md
            echo "<pre>" >> pr-results.md
            cat results.stdout >> pr-results.md
            echo "</pre>" >> pr-results.md

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: pr-results.md